name: CI Workflow
run-name: ðŸš€ CI Workflow ðŸš€

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}  # CondiÃ§Ã£o para pular o build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run build
        run: echo "Building the project..."

  deploy:
    runs-on: ubuntu-latest
    needs: [build]  # O deploy sÃ³ roda depois do build
    if: always()  # O deploy sempre serÃ¡ executado, mesmo se o build for pulado ou falhar
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy
        run: echo "Deploying the project..."
